eval File.read("../Podfile.shared.rb")

plugin "cocoapods-spm"

config_compact_spec(
  extra: lambda { |s|
    s.ios.deployment_target = "16.0"
  }
)

config_cocoapods_spm(
  dont_prebuild_macros: true,
  default_macro_config: "debug",
)

spm_pkg "SwiftUIX",
        :url => "https://github.com/SwiftUIX/SwiftUIX.git",
        :version => "0.1.9"
spm_pkg "SwiftyBeaver",
        :url => "https://github.com/SwiftyBeaver/SwiftyBeaver.git",
        :version => "2.0.0",
        :products => ["SwiftyBeaver"]

target "EX" do
  pod "Logger", :path => "LocalPods/Logger"
  pod "CommonUI", :path => "LocalPods/CommonUI"
  pod "Services", :path => "LocalPods/Services"
  pod "Orcam", :macro => {
    :git => "https://github.com/trinhngocthuyen/orcam.git",
    :branch => "main"
  }
  pod "MacroCodableKit", :macro => {
    :git => "https://github.com/mikhailmaslo/macro-codable-kit",
    :tag => "0.3.0"
  }
end

configure_post_install
