eval File.read("../Podfile.shared.rb")

plugin "cocoapods-spm"

config_cocoapods_spm(
  dont_prebuild_macros: true,
  default_macro_config: "debug",
)

target "EX" do
  pod "Services", :path => "LocalPods/Services"
  pod "Orcam", :macro => {
    :git => "https://github.com/trinhngocthuyen/orcam.git",
    :branch => "main"
  }
  pod "MacroCodableKit", :macro => {
    :git => "https://github.com/mikhailmaslo/macro-codable-kit",
    :tag => "0.3.0"
  }
end

configure_post_install
